/**
 * Заказ на ресурсы облака
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package Lesson09_hw.jaxrs;

import io.swagger.model.Cloud;
import io.swagger.model.Clouds;
import io.swagger.model.Error;
import io.swagger.model.Resources;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Заказ на ресурсы облака
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API tests for CloudsApi 
 */
public class CloudsApiTest {


    private CloudsApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("http://localhost:8080/api/v1/", CloudsApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Метод отмены заказа по ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelCloudByIdTest() {
        String cloudId = null;
        //api.cancelCloudById(cloudId);
        
        // TODO: test validations
        
        
    }
    /**
     * Метод создания заказа на облако
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCloudTest() {
        Error body = null;
        //Cloud response = api.createCloud(body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Метод получения списка ресурсов на облако
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCloudsTest() {
        //Resources response = api.getAllClouds();
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Метод получения заказа на облако по ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCloudByIdTest() {
        String cloudId = null;
        //Clouds response = api.getCloudById(cloudId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
}
