/*
 * Заказ на ресурсы облака
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Lesson09_hw.java;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Resources
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-15T12:32:25.602413532Z[GMT]")
public class Resources {
  /**
   * Операционная система сервера
   */
  @JsonAdapter(OSEnum.Adapter.class)
  public enum OSEnum {
    WINDOWS("Windows"),
    LINUX("Linux");

    private String value;

    OSEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static OSEnum fromValue(String input) {
      for (OSEnum b : OSEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<OSEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OSEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public OSEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return OSEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("OS")
  private OSEnum OS = null;

  @SerializedName("RAM")
  private String RAM = null;

  @SerializedName("HDD")
  private String HDD = null;

  @SerializedName("CPU")
  private String CPU = null;

  public Resources OS(OSEnum OS) {
    this.OS = OS;
    return this;
  }

   /**
   * Операционная система сервера
   * @return OS
  **/
  @Schema(required = true, description = "Операционная система сервера")
  public OSEnum getOS() {
    return OS;
  }

  public void setOS(OSEnum OS) {
    this.OS = OS;
  }

  public Resources RAM(String RAM) {
    this.RAM = RAM;
    return this;
  }

   /**
   * Get RAM
   * @return RAM
  **/
  @Schema(example = "128", required = true, description = "")
  public String getRAM() {
    return RAM;
  }

  public void setRAM(String RAM) {
    this.RAM = RAM;
  }

  public Resources HDD(String HDD) {
    this.HDD = HDD;
    return this;
  }

   /**
   * Get HDD
   * @return HDD
  **/
  @Schema(example = "128", required = true, description = "")
  public String getHDD() {
    return HDD;
  }

  public void setHDD(String HDD) {
    this.HDD = HDD;
  }

  public Resources CPU(String CPU) {
    this.CPU = CPU;
    return this;
  }

   /**
   * Get CPU
   * @return CPU
  **/
  @Schema(example = "128", required = true, description = "")
  public String getCPU() {
    return CPU;
  }

  public void setCPU(String CPU) {
    this.CPU = CPU;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resources resources = (Resources) o;
    return Objects.equals(this.OS, resources.OS) &&
        Objects.equals(this.RAM, resources.RAM) &&
        Objects.equals(this.HDD, resources.HDD) &&
        Objects.equals(this.CPU, resources.CPU);
  }

  @Override
  public int hashCode() {
    return Objects.hash(OS, RAM, HDD, CPU);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resources {\n");
    
    sb.append("    OS: ").append(toIndentedString(OS)).append("\n");
    sb.append("    RAM: ").append(toIndentedString(RAM)).append("\n");
    sb.append("    HDD: ").append(toIndentedString(HDD)).append("\n");
    sb.append("    CPU: ").append(toIndentedString(CPU)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
